## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [2]:
import numpy as np
array=np.arange(50,101)
array

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [2]:
a1=np.ones((3,3))
a2=np.pad(a1,pad_width=1,mode='constant',constant_values=0)
a2

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

In [3]:
list_=[1,2,3,4,5,6,7,8]
array=np.array(list_)
print(f'list to array: {array}')
tup=(8,4,6,1,2,3)
a1=np.array((tup)).reshape(2,3)
print(f'Tuple to array: {a1}')

print(np.asarray(list_))
print(np.asarray(tup).reshape(2,3))

list to array: [1 2 3 4 5 6 7 8]
Tuple to array: [[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [4]:
f=np.array([0. ,  12.,   45.21, 34.,   99.91])
print(f'Values in Fahrenheit degrees:{f}')
c= (f*5)/9-(32*5)/9
print(f'Values in  Centigrade degrees: {c}')

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [7]:
array=np.array([1,2,3],dtype=np.float64)
print(f'Size of the array: {array.size}')
print(f'Length of one array element in bytes: {array.itemsize}')
print(f'Total bytes consumed by the elements of the array:{array.nbytes}')

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Exercise 6: Get the unique elements of an array

In [9]:
l1=np.array([10,10,20 ,20, 30 ,30])
print(f'Original Array: {l1}')
print(f'Unique elements of the above array: {np.unique(l1)}')
l2=np.array([[1,1],[2,3]])
print(f'Original Array: {l2}')
print(f'Unique elements of the above array: {np.unique(l2)}')

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


## Exercise 7: Change the dimension of an array


In [4]:
a1=np.array([1, 2 ,3, 4, 5, 6, 7, 8, 9])
print(f'Original array: {a1}')
print('Change array shape to (3, 3) -> 3 rows and 3 columns')
a1.reshape(3,3)

Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [12]:
a1=np.linspace(2.5,6.5,30)
a1

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [21]:
array1=np.array([10,20,30])
array2=np.array([40,50,60])
a1=np.stack((array1,array2),axis=1)
a1

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [22]:
a1=np.zeros((5,5))
print('Original Array')
print(a1)
a1=a1+np.arange(5)
print('Row values ranging from 0 to 4.')
print(a1)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [23]:
a1=[ 3 , 5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51,
 54 ,55 ,57 ,60 ,63 ,65 ,66 ,69 ,70 ,72 ,75, 78 ,80 ,81 ,84 ,85 ,87 ,90 ,93 ,95 ,96 ,99]
sum=0
for i in a1:
    if i%3==0 or i%5==0:
        sum+=i
print(sum)

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [5]:
x = np.array([0,1,2,3])
print('One dimensional array:')
print(x)
y=np.array([[0,1,2,3],[4,5,6,7]])
print('Two dimensional array:')
print(y)
for a,b in np.nditer([x,[[y]]]):
    print(f'{a}:{b}')


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [6]:
a1=np.array([[0.42436315, 0.48558583 ,0.32924763],
 [0.7439979,0.58220701 ,0.38213418],
 [0.5097581,0.34528799, 0.1563123 ]])
print('Original array:')
print(a1)
a1[a1 > .5] =.5
print('Replace all elements of the said array with .5 which are greater than .5')
print(a1)
        

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [7]:
arr=np.empty([0,3],int)
print('Empty array:')
print(arr)
arr1=np.array([[10,20,30],[40,50,60]])
arr=np.append(arr,arr1,axis=0)
print('After adding two new arrays:')
print(arr)

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [8]:
ar1=np.array([1,2,3])
ar2=np.array([2,3,4])
print('Original arrays:')
print(ar1)
print(ar2)
print('Sequence of arrays along a new axis:')
print(np.stack((ar1,ar2)))

ar1=np.array([[1,2,3]])
ar2=np.array([[2,3,4]])
print('Original arrays:')
print(ar1.transpose())
print(ar2.transpose())
print('Sequence of arrays along a new axis:')
print(np.concatenate((ar1.T,ar2.T)))

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]
Original arrays:
[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
