In [1]:
#Numpy - Numerical Python - Arrays - linear Algebra, Matrices, Transformations (Fourier)
## 1) Memory Usage
import numpy as np 
import time
import sys 

In [9]:
from numpy import *

In [10]:
arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
import subadd as sd

In [2]:
array = np.arange(100)
print("The memory size of this particular array is:",array.size*array.itemsize)

The memory size of this particular array is: 400


In [3]:
list_ = range(0,100)
print("The memory size of this list here is:", sys.getsizeof(1)*len(list_))

The memory size of this list here is: 2800


In [4]:
## 2) Faster Computation: 
size = 100000

#Creating two lists 
list1 = range(size)
list2 = range(size)

#Creating two arrays 
arr1 = np.arange(size)
arr2 = np.arange(size)

In [5]:
start = time.time()
for x,y in zip(list1, list2):
    res = x+y

print("The time taken by lists:",(time.time()-start)*1000)

The time taken by lists: 41.88823699951172


In [6]:
start = time.time()
res = arr1+arr2
print("The time taken by arrays are:",(time.time()-start)*1000)

The time taken by arrays are: 0.9944438934326172


In [ ]:
'''
Install 
!pip install numpy==1.19.0
!conda install numpy --y 
!pip3 install numpy 
'''

In [13]:
#import 
import numpy as np

## Creating arrays

In [14]:
a1 = np.array([1,2,28])

In [15]:
a1

array([ 1,  2, 28])

In [16]:
type(a1)

numpy.ndarray

In [17]:
#nd - 'n' Dimentional Array - 1D, 2D, 3D (Tensors) - Row, Columns and the depth

In [18]:
lst = [1,2,"Batch15"]
type(lst[0])

int

In [32]:
arr = np.array([1,2,4.0,"Hello"])
print(type(arr[0]))

<class 'numpy.str_'>


In [33]:
print(np.__version__)

1.15.1


In [39]:
arr_2d = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [40]:
arr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [43]:
arr_2d[1,1]

6

In [38]:
arr_2d[1,1]

6

In [ ]:
#Create an array with shape 3x3
#Create an array with shape 2x4x4

## Functions involved in creating

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a = a.reshape((2,2,4))

In [3]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [51]:
#linspace -> This funct 
np.linspace(0.50,50.45,10)

array([ 0.5 ,  6.05, 11.6 , 17.15, 22.7 , 28.25, 33.8 , 39.35, 44.9 ,
       50.45])

In [53]:
np.arange(0,100,10) # Start, Stop and Step 

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Create an array with values ranging from 12 to 38 just the even numbers

In [54]:
#Zeros - Fill all the elements with zero 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
#Ones  - Fills the specified shape 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
a = np.ones((3,3))
x = np.pad(a,pad_width = 1,mode = 'constant',constant_values = 0)

In [60]:
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
#identity matrix - with just the diagonal elements as one
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
#Square matrix - rows and columns will be equal
#diagonal Matrix 
np.diag([1,2,4,5,6])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [65]:
#Operations with numpy array 
arr = np.array([24,12,11])
dup = arr
arr[0] = 55

In [66]:
print(arr)
print(dup)

[55 12 11]
[55 12 11]


In [68]:
#Operations with numpy array 
arr = np.array([24,12,11])
dup = arr.view()
arr[0] = 55

print(arr)
print(dup)

[55 12 11]
[55 12 11]


In [67]:
arr = np.array([24,12,11])
dup = arr.copy()
arr[0] = 55

print(arr)
print(dup)

[55 12 11]
[24 12 11]


In [69]:
arr

array([55, 12, 11])

In [70]:
for i in arr: 
    print(i)

55
12
11


In [71]:
arr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [73]:
for i in arr_2d:
    for j in i:
        print(j)

1
2
3
5
6
7
8
9
10


In [74]:
#Addition 
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

In [83]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [76]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [82]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [77]:
arr1+arr2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [78]:
np.add(arr1,arr2)

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [79]:
#Subtraction
arr1-arr2

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [80]:
np.subtract(arr1,arr2)

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [81]:
#Multiplication of each elements
arr1*arr2

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [84]:
np.multiply(arr1,arr2)

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [ ]:
#Convert a list into an array 
#Create a 2D array from a tuple

In [85]:
#Dot product 
np.dot(arr1,arr2)

array([[ 900, 1000, 1100, 1200],
       [2020, 2280, 2540, 2800],
       [3140, 3560, 3980, 4400],
       [4260, 4840, 5420, 6000]])

In [86]:
#Joining Two arrays

In [96]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([50,60,7,8])

np.stack((arr1,arr2))

array([[ 1,  2,  3,  5],
       [50, 60,  7,  8]])

In [90]:
res_array= np.stack((arr1,arr2),axis = 1)

In [92]:
res_array

array([[1, 5],
       [2, 6],
       [3, 7],
       [5, 8]])

In [91]:
np.transpose(res_array)

array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [93]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 5, 5, 6, 7, 8])

In [98]:
a = np.array([[1,2],[7,8]])
b = np.array([[5,6]])
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [7, 8],
       [5, 6]])

In [100]:
np.concatenate((a,b),axis = None)

array([1, 2, 7, 8, 5, 6])

In [101]:
np.concatenate((a,b.T),axis = 1)

array([[1, 2, 5],
       [7, 8, 6]])

In [97]:
np.sort(arr2)

array([ 7,  8, 50, 60])

In [103]:
arr

array([ 1,  2,  3,  5, 50, 60,  7,  8])

In [102]:
arr = np.concatenate((arr1,arr2))
np.array_split(arr,4)

[array([1, 2]), array([3, 5]), array([50, 60]), array([7, 8])]

In [105]:
arr = np.array([1,2,3,4,5,6,7])
np.array_split(arr,4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]